streams + attachment size check + attachment url in body
elasticio/aws-s3-component pull request #72
Opened 2022-05-13 08:03 UTC by if0s

2022-05-13 08:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/elasticio/aws-s3-component?pullRequest=72) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/elasticio/aws-s3-component?pullRequest=72) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/elasticio/aws-s3-component?pullRequest=72) it.</sub>

2022-05-13 08:55 UTC, shulkaolka requested changes
Is it necessary to up the major version? (2.0.0)

2022-05-13 08:55 UTC, shulkaolka commented on component.json
> +  "version": "2.0.0-dev.2",
please remove .dev

2022-05-13 08:55 UTC, shulkaolka commented on package.json
> +    "@elastic.io/component-commons-library": "2.1.0-dev.6",
please remove .dev

2022-05-13 10:19 UTC, if0s commented on component.json
> +  "version": "2.0.0-dev.2",
after QA, i will keep it in mind

2022-05-13 10:19 UTC, if0s commented on package.json
> +    "@elastic.io/component-commons-library": "2.1.0-dev.6",
waiting library release

2022-05-13 11:04 UTC, olegosh approved these changes

2022-05-13 11:05 UTC, shulkaolka commented on component.json
> +  "version": "1.5.0-dev.4",
-dev should be deleted

2022-05-17 12:51 UTC, if0s commented on package.json
> +    "@elastic.io/component-commons-library": "2.1.0-dev.6",
done

2022-05-17 12:51 UTC, if0s commented on component.json
> +  "version": "1.5.0-dev.4",
after QA

2022-05-20 09:06 UTC, if0s commented on component.json
> +  "version": "1.5.0-dev.4",
done

2022-05-20 09:07 UTC, merged